#!/usr/bin/env python3

import asyncio

import aioros
from std_msgs.msg import String


async def main(nh: aioros.NodeHandle):
    publisher: aioros.Publisher = await nh.create_publisher(
        'chatter',
        String)
    while True:
        publisher.publish(String(data='Hello world'))
        await asyncio.sleep(0.1)


if __name__ == '__main__':
    aioros.run_until_complete(main, 'talker')
